blank_issues_enabled: false
contact_links:
  - name: Questions (Q&A)
    url: https://github.com/joaomelo/calystone/discussions/categories/q-a
    about: Ask how-to questions or usage doubts here.
  - name: Announcements
    url: https://github.com/joaomelo/calystone/discussions/categories/announcements
    about: Important updates.