name: close-prs
on:
  pull_request_target:
    types: [opened, reopened]
permissions:
  pull-requests: write
jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const number = context.payload.number;
            const body = [
              "Thanks for your interest! Calystone is a small hobby project and is not accepting code contributions at this time.",
              "This PR will now be closed. Thanks for understanding! 🙏"
            ].join("\n");
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: number,
              body
            });
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: number,
              state: 'closed'
            });
