name: deploy

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'assets/**'
      - 'e2e/**'
      - '.github/workflows/deploy.yml'
      - '.release-it.json'
      - 'cypress.config.js'
      - 'firebase.json'
      - 'package-lock.json'
      - 'package.json'
      - 'tsconfig*.json'
      - 'vite.config.*'
      - 'vitest.setup.*'

jobs:
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      VITE_ONE_DRIVE_CLIENT_ID: ${{ secrets.VITE_ONE_DRIVE_CLIENT_ID }}
      VITE_DROPBOX_CLIENT_ID: ${{ secrets.VITE_DROPBOX_CLIENT_ID }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'          
      - run: npm ci
      - run: npm run quality
        env:
          VITE_ENABLE_MEMORY: true
          VITE_PRELOAD_ENABLED: false
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bundle-report
          path: dist/bundle-report.html
          retention-days: 5             
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-media
          path: |
            e2e/videos
            e2e/screenshots
          retention-days: 3
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_ENABLE_MEMORY: false
          VITE_LOGGER_LEVEL: 7
          VITE_PRELOAD_ENABLED: true
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CALYSTONE_A5BDF }}"
          projectId: calystone-a5bdf
          channelId: live